### ISSUE TITLE
Laden des Essen am kommenden Donnerstag (08. Juni)

### ISSUE THREAD

**Issue by alkock** [HAWHHCalendarBot/TelegramBot#107]
Beim Laden des Essen vom 08 Juni 2022 erhalte ich folgenden Fehler
```
Error: Call to 'editMessageText' failed! (400: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 577)
```

Der Fehler lässt sich nur an diesem Tag replizieren. Versucht habe ich den Mittwoch und Freitag, diese klappen ohne Probleme.

**Comment by EdJoPaTo** [comment]
Scheinbar passiert das auch für die Mensa Berliner Tor am 9.6. ohne Inhaltsstoffe anzuzeigen. Wenn man die Inhaltsstoffe in den Einstellungen aktiviert, geht es.

Ich schaue mir das mal an, danke fürs melden!

**Comment by EdJoPaTo** [comment]
fixed via 9f9747a0bdaace6a38fb0c6c1089a0a1a2a65c6d

Danke nochmal fürs melden!
