### ISSUE TITLE
Kann keine weitere Kurse hinzufügen nach falscher Eingabe von Filter

### ISSUE THREAD

**Issue by youssefbenlemlih** [HAWHHCalendarBot/TelegramBot#22]
Ich habe die Kurse nach `?` gefiltert und jetzt kann ich keinen weiteren Kurs hinzufügen, auch wenn ich das Bot neu starte.
![image](https://user-images.githubusercontent.com/9917897/113394337-54166d00-9398-11eb-9288-6b3fff8237b0.png)

**Comment by EdJoPaTo** [comment]
Danke fürs Bescheid sagen!
