### ISSUE TITLE
Bei zusätzlichem Termin Monats-Button/Anzeige mit Offset von einem Monat

### ISSUE THREAD

**Issue by stroebjo** [HAWHHCalendarBot/TelegramBot#23]
Beim Anlegen eines zusätzlichen Termins für eine Veranstaltung stimmt der Button für die Auswahl des Monats nicht mit der angezeigten Zusammenfassung darüber überein. Wenn der Button z. B. auf `April` gestellt ist, steht in der Zusammenfassung `Mai`.

**Comment by EdJoPaTo** [comment]
JavaScripts Date ist 0 basiert, meine Logik 1 basiert…

Danke fürs Bescheid sagen!
