### ISSUE TITLE
Zusätzlicher Termin Startzeit wird nicht gespeichert

### ISSUE THREAD

**Issue by stroebjo** [HAWHHCalendarBot/TelegramBot#52]
Wenn man bei einer Veranstaltung einen zusätzlichen Termin erstellt, wird die manuell eingestellte Start-Uhrzeit nicht gespeichert. In der Übersicht erscheint sie korrekt, nach "Fertig stellen" wird sie allerdings auf 9:30 Uhr gesetzt. 

Ändert man die Startzeit gar nicht (aktuelle Uhrzeit) scheint sie gespeichert zu werden.

**Comment by EdJoPaTo** [comment]
abea0b1f9f34d70d990c696b040d544b390923d7 sollte schon mal das Zeitzonen Problem beheben, damit ist das nicht mehr ganz so verwirrend.

Trotzdem steht während dem Generieren eines neuen Termins noch das initiale Datum oben, während die Startzeit als Änderung aufgeführt ist. Sobald man dies anlegt, steht die Startzeit oben und nicht mehr als Änderung.

Das ist ein wenig seltsam mit der Logik im Hintergrund, müsste ich mir mal überlegen, wie man das sinnvoller löst. Das ist aber nur noch ein Display Problem.

Außer ich übersehe noch was?

**Comment by stroebjo** [comment]
Hat super funktioniert. Vielen Dank! Das die initiale Zeit in der Headline steht, finde ich gar nicht so schlimm. Man fokussiert sich ja eh auf Zusammenfassung im Text.

**Comment by EdJoPaTo** [comment]
Dann akzeptiere ich das einfach erst mal so wie es ist, vielleicht bedarf es ja in Zukunft noch mal einer Optimierung, vielleicht mache ich es dann mal besser.
