### ISSUE TITLE
WP-A4

### ISSUE THREAD

**Issue by Regenhardt** [HAWHHCalendarBot/TelegramBot#84]
Moin,
WP-A4, embedded machine learning bei Prof Pareigis, wird jetzt jeden Dienstag und Freitag früh ab 8:30 bis 11:30 stattfinden. Das Praktikum ist da integriert. Es gibt eine Gruppe für Dienstag und eine für Freitag. 
Wäre gut wenn der Kalenderbot das so wiederspiegeln kann, also nur zwei Gruppen für die Veranstaltung quasi, eine Dienstag eine Freitag.

**Comment by EdJoPaTo** [comment]
Erstmal natürlich danke für deinen Willen, Dinge verbessern zu wollen!

Angesehen von den [AdditionalEvents](https://github.com/HAWHHCalendarBot/AdditionalEvents) würde ich keine Anpassungen für alle machen, da das meistens schwer nachzuvollziehen ist, ob das wirklich stimmt.

Der Idealfall wäre, wenn das in den offiziellen Plan kommt, sodass auch die Quell ICS Dateien das genau so widerspiegeln. Dann gibt es die wenigsten Missverständnisse und auch die, die den Kalenderbot nicht benutzen, profitieren davon.

Ansonsten kannst du Änderungen an Veranstaltungsterminen hinzufügen (oder neue Termine hinzufügen) und diese Änderungen auch (in anderen Chats) teilen. Andere können diese Änderung dann bei sich ebenfalls hinzufügen.
Hier klingt das aber mehr nach einer größeren Änderung vieler Termine? Bin mir nicht sicher wie gut sich dass dann eignet.

Ich hoffe, ich konnte weiterhelfen bzw meine Gedanken dazu teilen?

**Comment by Regenhardt** [comment]
Hat geklappt, danke für die Info, der offizielle Vorlesungsplan wurde angepasst :)
