### ISSUE TITLE
Änderungen, bei Startzeit geht nur noch 8 Uhr

### ISSUE THREAD

**Issue by stroebjo** [HAWHHCalendarBot/TelegramBot#9]
Wenn ich eine Änderung über eine geänderte Startzeit hinzufügen will, zeigt er immer 8 Uhr an, egal was ich ausgewählt habe. Das grüne Häkchen ist immer bei der 8. 

Bei der Minuten Zeit funktioniert es aber ganz normal, da wechselt das grüne Häkchen erwartungskonform.

**Comment by EdJoPaTo** [comment]
Danke fürs melden! Hab den Fehler gefunden und behoben.
